/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hospitalmanagementsystem;

import static hospitalmanagementsystem.AddPatient.imageData;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author abiolam
 */
public class UpdatePatient extends javax.swing.JDialog {

    /**
     * Creates new form UpdatePatient
     */
     public static String patientId;
    public UpdatePatient(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         Patient ep = new PatientDatabseManager().getPatient(patientId);
        txtUpID.setText(ep.getPatientId());
        txtUpSur.setText(ep.getSurname());
        txtUpFir.setText(ep.getFirstname());
        txtUpOther.setText(ep.getOthername());
        cmbUpGen.setSelectedItem(ep.getGender().toUpperCase());
        txtUpPhn.setText(ep.getPhonenumber());
        txtUpAdd.setText(ep.getAddress());
       // if(imageData != null){
            Image Img = new ImageIcon(ep.getPhoto()).getImage().getScaledInstance(UpPass.getWidth(),UpPass.getHeight(), Image.SCALE_DEFAULT);
            UpPass.setIcon(new ImageIcon(Img));
       // }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUpID = new javax.swing.JTextField();
        txtUpSur = new javax.swing.JTextField();
        txtUpFir = new javax.swing.JTextField();
        txtUpOther = new javax.swing.JTextField();
        txtUpPhn = new javax.swing.JTextField();
        cmbUpGen = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtUpAdd = new javax.swing.JTextArea();
        UpPanel = new javax.swing.JPanel();
        UpPass = new javax.swing.JLabel();
        UpBrowse = new javax.swing.JButton();
        UpUpdate = new javax.swing.JButton();
        UpCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("UPDATE PATIENT");

        jLabel1.setText("Patient ID");

        jLabel2.setText("Surname");

        jLabel3.setText("Firstname");

        jLabel4.setText("Othername");

        jLabel5.setText("Gender");

        jLabel6.setText("Phonenumber");

        jLabel7.setText("Address");

        txtUpID.setEditable(false);

        cmbUpGen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select...", "MALE", "FEMALE" }));

        txtUpAdd.setColumns(20);
        txtUpAdd.setRows(5);
        jScrollPane1.setViewportView(txtUpAdd);

        UpPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("PASSPORT"));

        javax.swing.GroupLayout UpPanelLayout = new javax.swing.GroupLayout(UpPanel);
        UpPanel.setLayout(UpPanelLayout);
        UpPanelLayout.setHorizontalGroup(
            UpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UpPass, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );
        UpPanelLayout.setVerticalGroup(
            UpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpPanelLayout.createSequentialGroup()
                .addComponent(UpPass, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addContainerGap())
        );

        UpBrowse.setText("BROWSE");
        UpBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpBrowseActionPerformed(evt);
            }
        });

        UpUpdate.setText("UPDATE");
        UpUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpUpdateActionPerformed(evt);
            }
        });

        UpCancel.setText("CANCEL");
        UpCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUpPhn)
                            .addComponent(txtUpID)
                            .addComponent(txtUpSur)
                            .addComponent(txtUpFir)
                            .addComponent(txtUpOther)
                            .addComponent(cmbUpGen, 0, 160, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(UpBrowse))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(UpUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(UpCancel))
                            .addComponent(UpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UpUpdate)
                        .addComponent(UpCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel1)
                                                    .addComponent(txtUpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel2))
                                            .addComponent(txtUpSur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(txtUpFir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(txtUpOther, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(UpPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(cmbUpGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(UpBrowse)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtUpPhn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpCancelActionPerformed
        dispose();
    }//GEN-LAST:event_UpCancelActionPerformed

    private void UpUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpUpdateActionPerformed
         Patient e = new Patient();
        e.setPatientId(txtUpID.getText());
        e.setSurname(txtUpSur.getText());
        e.setFirstname(txtUpFir.getText());
        e.setOthername(txtUpOther.getText());
        e.setGender(cmbUpGen.getSelectedItem().toString());
        e.setPhonenumber(txtUpPhn.getText());
        e.setAddress(txtUpAdd.getText());
         if(imageData != null){
            e.setPhoto(imageData);
        }else{
            e.setPhoto(new byte[]{});
        }
        PatientDatabseManager manager = new PatientDatabseManager();
       manager.update(e);
        JOptionPane.showMessageDialog(this, "Record updated", "Update Employee", JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }//GEN-LAST:event_UpUpdateActionPerformed

    private void UpBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpBrowseActionPerformed
          SelectPassport sp = new SelectPassport(null, true);
        sp.setLocationRelativeTo(null);
        sp.setVisible(true);
        if(imageData != null){
            Image Img = new ImageIcon(imageData).getImage().getScaledInstance(UpPass.getWidth(),UpPass.getHeight(), Image.SCALE_DEFAULT);
            UpPass.setIcon(new ImageIcon(Img));
        }
    }//GEN-LAST:event_UpBrowseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdatePatient dialog = new UpdatePatient(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpBrowse;
    private javax.swing.JButton UpCancel;
    private javax.swing.JPanel UpPanel;
    private javax.swing.JLabel UpPass;
    private javax.swing.JButton UpUpdate;
    private javax.swing.JComboBox cmbUpGen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtUpAdd;
    private javax.swing.JTextField txtUpFir;
    private javax.swing.JTextField txtUpID;
    private javax.swing.JTextField txtUpOther;
    private javax.swing.JTextField txtUpPhn;
    private javax.swing.JTextField txtUpSur;
    // End of variables declaration//GEN-END:variables
}
